title:              Emily & Nick
description:        Emily and Nick get married!

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

includes_dir: /_includes
